---
Name: cookieconsent
---
Innoweb\CookieConsent\CookieConsent:
  cookies:
    Necessary:
      local:
        - PHPSESSID
        - CookieConsent
    #Analytics
    #Marketing
    #External
    #Preferences

SilverStripe\Control\Director:
  rules:
    acceptAllCookies: PageController

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Innoweb\CookieConsent\Extensions\ContentControllerExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Innoweb\CookieConsent\Extensions\SiteConfigExtension

---
Name: cookieconsent-cookie
After: cookie
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Cookie_Backend: Innoweb\CookieConsent\Control\CookieJar
